// Code generated by protoc-gen-enum-desc-go. DO NOT EDIT.
// versions:
// - protoc-gen-enum-desc-go v0.1.0
// - protoc             (unknown)
// source: kazweb/example.proto

package kazweb

// Enum description value maps for Enum.
var Enum_desc = map[int32]string{
	0: "Plan A",
	1: "Plan B",
}

func (x Enum) Desc() string {
	if v, ok := Enum_desc[int32(x)]; ok {
		return v
	}
	return ""
}
