// Code generated by protoc-gen-sam-go. DO NOT EDIT.
// versions:
// - protoc-gen-sam-go v0.1.0
// - protoc             (unknown)
// source: kazweb/example.proto

package kazweb

import (
	context "context"
)

type CanEcho interface {
	Echo(ctx context.Context, in *EchoRequest) (*EchoResponse, error)
}

type EchoFunc func(ctx context.Context, in *EchoRequest) (*EchoResponse, error)
